DROP TABLE IF EXISTS DNA_RNF.RNF_USER;

CREATE TABLE DNA_RNF.RNF_USER AS
SELECT DISTINCT ID::TEXT AS USER_ID,
    TITLE::TEXT,
    BADGE_TEXT::TEXT,
    IS_ACTIVE::BOOLEAN,
    USER_TYPE::TEXT,
    MANAGER_ID::TEXT,
    CONTACT_ID::TEXT,
    PARTNER_TYPE_C::TEXT,
    ACCOUNT_ID::TEXT
FROM dna_etl.SFDC_USER;