DROP TABLE IF EXISTS DNA_RNF.RNF_TASK_OPPORTUNITY;

CREATE TABLE DNA_RNF.RNF_TASK_OPPORTUNITY AS
SELECT DISTINCT ID::TEXT AS TASK_ID,
    ACCOUNT_ID::TEXT AS ACCOUNT_ID,
    OPPORTUNITY_ID::TEXT AS OPPORTUNITY_ID,
    ACTIVITY_TYPE_C::TEXT AS ACTIVITY_TYPE_C,
    ACTIVITY_DATE::TIMESTAMP WITHOUT TIME ZONE AS ACTIVITY_DATE,
    STATUS::TEXT AS STATUS, 
    TASK_SUBTYPE::TEXT AS TASK_SUBTYPE,
    CREATED_BY_ROLE_NAME_C::TEXT AS CREATED_BY_ROLE_NAME_C,
    WHO_ID::TEXT as WHO_ID
FROM ( select o.id as opportunity_id, t.* 
from dna_etl.SFDC_TASK t, dna_etl.SFDC_OPPORTUNITY o
where not t.is_deleted::boolean and not o.is_deleted::boolean
and t.account_id = o.account_id
and t.what_id = o.id) T;
