DROP TABLE IF EXISTS DNA_RNF.RNF_ACCOUNT;

CREATE TABLE DNA_RNF.RNF_ACCOUNT AS
SELECT DISTINCT ID::TEXT AS ACCOUNT_ID,
    CREATED_DATE::TIMESTAMP WITHOUT TIME ZONE AS ACCOUNT_CREATED_DATE,
    OWNER_THEATER_C::TEXT AS DNA_CUSTOM_AC_OWNER_THEATER,
    ANNUAL_REVENUE::DOUBLE PRECISION AS DNA_STD_AC_ANNUAL_REVENUE,
    NUMBER_OF_EMPLOYEES::BIGINT AS DNA_STD_AC_NUMBER_OF_EMPLOYEES,
    INDUSTRY::TEXT AS DNA_STD_AC_INDUSTRY,
    INDUSTRY_CATEGORY::TEXT AS DNA_STD_AC_INDUSTRY_GROUPS,
    RUBRIK_TAM_C::DOUBLE PRECISION AS RUBRIK_TAM_C,
    PRODUCTS_INSTALLED_C::TEXT AS PRODUCTS_INSTALLED_C,
    ACCOUNT_TIER_C::TEXT AS ACCOUNT_TIER_C,
    MICROSOFT_ACCOUNT_FLAG_C::TEXT AS MICROSOFT_ACCOUNT_FLAG_C,
    NET_APP_ACCOUNT_C::TEXT AS NET_APP_ACCOUNT_C,
    GSI_PARTNER_FLAG_C::TEXT AS PARTNER_FLAG_C,
    IS_PARTNER::BOOLEAN AS IS_PARTNER
FROM dna_etl.sfdc_account
LEFT JOIN dna_rnf.ACCOUNT_INDUSTRY_MAP ON INDUSTRY = ANY(INDUSTRY_FINE)